model nitri
  parameter Real Y_h = 0.67 "Heterotrophic Yield [g Xbh COD formed/(g COD utilised)]";
  parameter Real Y_a = 0.24 "Autotrophic Yield [g Xba COD formed/(g N utilised)]";
  parameter Real f_p = 0.08 "Fraction of biomass to particulate products [-]";
  parameter Real i_xb = 0.08 "Fraction nitrogen in biomass [g N/(g COD)]";
  parameter Real i_xp = 0.06 "Fraction nitrogen in particulate products [g N/(g COD)]";
  parameter Real mu_h_T = 4.0 "Maximum heterotrophic growth rate at T=15 deg C [day^-1]";
  parameter Real b_h_T = 0.3 "Heterotrophic decay rate at T=15 deg C [day^-1]";
  parameter Real mu_a_T = 0.5 "Maximum autotrophic growth rate at T=15 deg C[day^-1]";
  parameter Real b_a_T = 0.05 "Autotrophic decay rate at T=15 deg C [day^-1]";
  parameter Real k_a_T = 0.05 "Ammonification rate at T=15 deg C [m3/(g COD day)]";
  parameter Real k_h_T = 3.0 "Maximum specific hydrolysis rate at T=15 deg C [g Xs/(g Xbh COD day)]";
  parameter Real K_x_T = 0.1 "Half-saturation (hydrolysis) at T=15 deg C [g Xs/(g Xbh COD)]";
  parameter Real K_nh = 0.5 "Half-saturation (auto. growth) [g NH-N/m3]";
  parameter Real K_s = 10.0 "Half-saturation (hetero. growth) [g COD/m3]";
  parameter Real K_oh = 0.2 "Half-saturation (hetero. oxygen) [g O/m3]";
  parameter Real K_no = 0.5 "Half-saturation (nitrate) [g NO-N/m3]";
  parameter Real K_oa = 0.4 "Half-saturation (auto. oxygen) [g O/m3]";
  parameter Real ny_g = 0.8 "Anoxic growth rate correction factor [-]";
  parameter Real ny_h = 0.8 "Anoxic hydrolysis rate correction factor [-]";
  input Modelica.Blocks.Interfaces.RealInput T;
  parameter Modelica.SIunits.Volume V = 1333 "Volume of nitrification tank";
  parameter Real alpha = 240 "Oxygen transfer factor";
  parameter Modelica.SIunits.Length de = 4.5 "depth of aeration";
  parameter Real R_air = 23.5 "specific oxygen feed factor [gO2/(m^3*m)]";

  Real mu_h "Maximum heterotrophic growth rate f(T) [day^-1]";
  Real b_h "Heterotrophic decay rate f(T) [day^-1]";
  Real mu_a "Maximum autotrophic growth rate f(T) [day^-1]";
  Real b_a "Autotrophic decay rate f(T) [day^-1]";
  Real k_a "Ammonification rate f(T) [m3/(g COD day)]";
  Real k_h "Maximum specific hydrolysis rate f(T) [g Xs/(g Xbh COD day)]";
  Real K_x "Half-saturation (hydrolysis) f(T) [g Xs/(g Xbh COD)]";
  WasteWater.WasteWaterUnits.MassConcentration Si(fixed = true) "Soluble inert organic matter";
  WasteWater.WasteWaterUnits.MassConcentration Ss(fixed = true) "Readily biodegradable substrate";
  WasteWater.WasteWaterUnits.MassConcentration Xi(fixed = true) "Particulate inert organic matter";
  WasteWater.WasteWaterUnits.MassConcentration Xs(fixed = true) "Slowly biodegradable substrate";
  WasteWater.WasteWaterUnits.MassConcentration Xbh(fixed = true) 
    "Active heterotrophic biomass";
  WasteWater.WasteWaterUnits.MassConcentration Xba(fixed = true) 
    "Active autotrophic biomass";
  WasteWater.WasteWaterUnits.MassConcentration Xp(fixed = true) "Particulate products from biomass decay";
  WasteWater.WasteWaterUnits.MassConcentration So(fixed = true) "Dissolved oxygen";
  WasteWater.WasteWaterUnits.MassConcentration Sno(fixed = true) 
    "Nitrate and nitrite nitrogen";
  WasteWater.WasteWaterUnits.MassConcentration Snh(fixed = true) 
    "Ammonium nitrogen";
  WasteWater.WasteWaterUnits.MassConcentration Snd(fixed = true) 
    "Soluble biodegradable organic nitrogen";
  WasteWater.WasteWaterUnits.MassConcentration Xnd(fixed = true) 
    "Particulate biodegradable organic nitrogen";
  WasteWater.WasteWaterUnits.Alkalinity Salk(fixed = true) "Alkalinity";
  Real p1;
  Real p2;
  Real p3;
  Real p4;
  Real p5;
  Real p6;
  Real p7;
  Real p8;
  Real r1;
  Real r2;
  Real r3;
  Real r4;
  Real r5;
  Real r6;
  Real r7;
  Real r8;
  Real r9;
  Real r10;
  Real r11;
  Real r12;
  Real r13;
  Real inputSi;
  Real inputSs;
  Real inputXi;
  Real inputXs;
  Real inputXbh;
  Real inputXba;
  Real inputXp;
  Real inputSo;
  Real inputSno;
  Real inputSnh;
  Real inputSnd;
  Real inputXnd;
  Real inputSalk;
  Real aeration;
  WasteWater.WasteWaterUnits.VolumeFlowRate In.Q;
  WasteWater.WasteWaterUnits.MassConcentration In.Si;
  WasteWater.WasteWaterUnits.MassConcentration In.Ss;
  WasteWater.WasteWaterUnits.MassConcentration In.Xi;
  WasteWater.WasteWaterUnits.MassConcentration In.Xs;
  WasteWater.WasteWaterUnits.MassConcentration In.Xbh;
  WasteWater.WasteWaterUnits.MassConcentration In.Xba;
  WasteWater.WasteWaterUnits.MassConcentration In.Xp;
  WasteWater.WasteWaterUnits.MassConcentration In.So;
  WasteWater.WasteWaterUnits.MassConcentration In.Sno;
  WasteWater.WasteWaterUnits.MassConcentration In.Snh;
  WasteWater.WasteWaterUnits.MassConcentration In.Snd;
  WasteWater.WasteWaterUnits.MassConcentration In.Xnd;
  WasteWater.WasteWaterUnits.Alkalinity In.Salk;
  WasteWater.WasteWaterUnits.VolumeFlowRate Out.Q;
  WasteWater.WasteWaterUnits.MassConcentration Out.Si;
  WasteWater.WasteWaterUnits.MassConcentration Out.Ss;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xi;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xs;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xbh;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xba;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xp;
  WasteWater.WasteWaterUnits.MassConcentration Out.So;
  WasteWater.WasteWaterUnits.MassConcentration Out.Sno;
  WasteWater.WasteWaterUnits.MassConcentration Out.Snh;
  WasteWater.WasteWaterUnits.MassConcentration Out.Snd;
  WasteWater.WasteWaterUnits.MassConcentration Out.Xnd;
  WasteWater.WasteWaterUnits.Alkalinity Out.Salk;
  WasteWater.WasteWaterUnits.VolumeFlowRate MeasurePort.Q;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Si;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Ss;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xi;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xs;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xbh;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xba;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xp;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.So;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Sno;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Snh;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Snd;
  WasteWater.WasteWaterUnits.MassConcentration MeasurePort.Xnd;
  WasteWater.WasteWaterUnits.Alkalinity MeasurePort.Salk;
  WasteWater.WasteWaterUnits.MassConcentration So_sat "Dissolved oxygen saturation";

// Equations and algorithms

  // This model
  // class WasteWater.ASM1.nitri
    // extends WasteWater.ASM1.Interfaces.ASM1base
    equation
      mu_h = mu_h_T;
      b_h = b_h_T;
      mu_a = mu_a_T;
      b_a = b_a_T;
      k_a = k_a_T;
      k_h = k_h_T;
      K_x = K_x_T;
      p1 = mu_h*(Ss/(K_s+Ss))*(So/(K_oh+So))*Xbh;
      p2 = mu_h*(Ss/(K_s+Ss))*(K_oh/(K_oh+So))*(Sno/(K_no+Sno))*ny_g*Xbh;
      p3 = mu_a*(Snh/(K_nh+Snh))*(So/(K_oa+So))*Xba;
      p4 = b_h*Xbh;
      p5 = b_a*Xba;
      p6 = k_a*Snd*Xbh;
      p7 = k_h*(Xs/Xbh/(K_x+Xs/Xbh))*(So/(K_oh+So)+ny_h*(K_oh/(K_oh+So))*(Sno/(
        K_no+Sno)))*Xbh;
      p8 = p7*Xnd/Xs;
      r1 = 0;
      r2 = (( -p1)-p2)/Y_h+p7;
      r3 = 0;
      r4 = (1-f_p)*(p4+p5)-p7;
      r5 = p1+p2-p4;
      r6 = p3-p5;
      r7 = f_p*(p4+p5);
      r8 = ( -(1-Y_h)/Y_h*p1)-(4.57-Y_a)/Y_a*p3;
      r9 = ( -(1-Y_h)/(2.86*Y_h)*p2)+p3/Y_a;
      r10 = ( -i_xb*(p1+p2))-(i_xb+1/Y_a)*p3+p6;
      r11 = ( -p6)+p8;
      r12 = (i_xb-f_p*i_xp)*(p4+p5)-p8;
      r13 = ( -i_xb/14*p1)+((1-Y_h)/(40.04*Y_h)-i_xb/14)*p2-(i_xb/14+1/(7*Y_a))*
        p3+p6/14;
      der(Si) = inputSi+r1;
      der(Ss) = inputSs+r2;
      der(Xi) = inputXi+r3;
      der(Xs) = inputXs+r4;
      der(Xbh) = inputXbh+r5;
      der(Xba) = inputXba+r6;
      der(Xp) = inputXp+r7;
      der(So) = inputSo+r8+aeration;
      der(Sno) = inputSno+r9;
      der(Snh) = inputSnh+r10;
      der(Snd) = inputSnd+r11;
      der(Xnd) = inputXnd+r12;
      der(Salk) = inputSalk+r13;
      Out.Q+In.Q = 0;
      Out.Si = Si;
      Out.Ss = Ss;
      Out.Xi = Xi;
      Out.Xs = Xs;
      Out.Xbh = Xbh;
      Out.Xba = Xba;
      Out.Xp = Xp;
      Out.So = So;
      Out.Sno = Sno;
      Out.Snh = Snh;
      Out.Snd = Snd;
      Out.Xnd = Xnd;
      Out.Salk = Salk;
      MeasurePort.Si = Si;
      MeasurePort.Ss = Ss;
      MeasurePort.Xi = Xi;
      MeasurePort.Xs = Xs;
      MeasurePort.Xbh = Xbh;
      MeasurePort.Xba = Xba;
      MeasurePort.Xp = Xp;
      MeasurePort.So = So;
      MeasurePort.Sno = Sno;
      MeasurePort.Snh = Snh;
      MeasurePort.Snd = Snd;
      MeasurePort.Xnd = Xnd;
      MeasurePort.Salk = Salk;
    // end of extends 
  equation
    So_sat = 13.51474512;

end nitri;
